- name: Installation du serveur
  hosts: all
  tasks:
    - name: Installation de vm
      proxmox_kvm:
       api_user    : root@pam
       api_password: itescia
       api_host    : 172.16.203.161
       clone       : Ubuntu-srv-template
       node        : pve
       name        : Ubuntu-run
    - name: wait 30
      wait_for:
        timeout: 30
      delegate_to: localhost
    - name: start VM
      proxmox_kvm:
       api_user    : root@pam
       api_password: itescia
       api_host    : 172.16.203.161
       name        : Ubuntu-srv-template
       node        : pve
       state       : started
